version: '3.8'

services:
  web:
    image: "sunraize/test-php:latest"
    container_name: php_container
    volumes:
      - ./src/photos:/var/www/html/photos
    ports:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
