name: CI to Docker Hub and Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourusername/yourappname:latest

    - name: Copy Docker Compose file
      run: scp docker-compose.yml user@server:/path/to/yourapp/

    - name: Deploy to Server
      run: |
        ssh user@server "docker pull yourusername/yourappname:latest && \
                         sed -i 's/image: yourusername\\/yourappname:.*/image: yourusername\\/yourappname:latest/' /path/to/yourapp/docker-compose.yml && \
                         docker-compose -f /path/to/yourapp/docker-compose.yml up -d"
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
